name: Generate Snake
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update snake
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2.2.1
        id: snake-gif
        with:
          github_user_name: ozandogrultan
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: readme
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
